services:
  backend:
    # Use Docker Hub tags for public pushing/pulling via Jenkins
    image: ${DOCKER_USERNAME:-mayankc1533262}/stayngo-backend:latest
    container_name: stayngo-backend
    restart: always
    ports:
      - "5001:5001"
    env_file:
      - .env

  frontend:
    image: ${DOCKER_USERNAME:-mayankc1533262}/stayngo-frontend:latest
    container_name: stayngo-frontend
    restart: always
    ports:
      - "3000:3000"
    env_file:
      - .env
